### PR TITLE
UI branch

### PR DESCRIPTION
**Pull request by z4cope**
- Installed Webpack and configured it.
- Installed Linters
- Added Markup & some styles

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @z4cope, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Ouch-gifs-38715704-365-199

You have submitted a project that has linters not properly set up. Considering that this is a HTML, CSS and JavaScript project, [this](https://github.com/microverseinc/linters-config/tree/master/html-css-js) is the required linters configuration to use but you seem to have used [this](https://github.com/microverseinc/linters-config/tree/master/html-css).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by z4cope** [comment]
@emmiiorji 
Thank you so much for your review :D, can you please point to the exact installation that I'm using because I'm 100% sure that Linters is working as expected.

**Comment by emmiiorji** [comment]
Hi @z4cope,

Thanks for your reply.

Kindly take a look at the difference between your [linters.yml](https://github.com/z4cope/score-leaderboard/blob/ui-branch/.github/workflows/linters.yml) and the correct [linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) for a HTML, CSS and JavaScript project.

Also, take a look at the difference between your [eslintrc.json](https://github.com/z4cope/score-leaderboard/blob/ui-branch/.eslintrc.json) and [that](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.eslintrc.json) of the correct config.

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @z4cope, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
